version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      RACK_ENV: production
      RAILS_ENV: production
      APP_DATABASE_HOST: db
      APP_DATABASE_USER: root
      APP_DATABASE_PASSWORD: 3x4mpl3p4S5w3Rd
      RAILS_LOG_TO_STDOUT: 1
    depends_on:
      - db
    networks:
      - db-tier
    links:
      - db:db

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_ROOT_PASSWORD: 3x4mpl3p4S5w3Rd
    networks:
      - db-tier

networks:
  db-tier:
    driver: bridge